"""Base strategy interface."""

from __future__ import annotations

import abc
from dataclasses import dataclass


@dataclass
class SignalOutput:
    """A trading signal generated by a strategy."""

    ticker: str
    direction: str  # "long" | "short" | "flat"
    strength: float  # 0.0 to 1.0


class BaseStrategy(abc.ABC):
    """Abstract base class for trading strategies."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Return the strategy name."""
        ...

    @abc.abstractmethod
    def generate_signals(
        self, definition: dict, current_prices: dict[str, float]
    ) -> list[SignalOutput]:
        """Generate trading signals given a strategy definition and current prices."""
        ...
